import { chromium } from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const root = path.resolve('dist');
const mime = {'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg'};
const srv = http.createServer((q,s)=>{ let p=decodeURIComponent(q.url.split('?')[0]); const f=path.join(root,p); if(!fs.existsSync(f)||fs.statSync(f).isDirectory()){s.writeHead(404);return s.end();} s.writeHead(200,{'content-type':mime[path.extname(f)]||'application/octet-stream'}); fs.createReadStream(f).pipe(s);}).listen(0);
const b = await chromium.launch(); const p = await b.newPage({viewport:{width:1440,height:900}});
const errs=[]; p.on('console',m=>{if(['error','warning'].includes(m.type())) errs.push(m.text())}); p.on('pageerror',e=>errs.push('PAGEERROR '+e.message));
await p.goto(`http://localhost:${srv.address().port}/page.html?static`); await p.waitForFunction('window.ready===true'); await p.waitForTimeout(1200);
await p.screenshot({path:'/tmp/theme_hero.png'});
await p.evaluate(()=>document.querySelector('#greeting').scrollIntoView({behavior:'instant'})); await p.waitForTimeout(400);
await p.screenshot({path:'/tmp/theme_greeting.png'});
await p.evaluate(()=>document.querySelector('#how').scrollIntoView({behavior:'instant'})); await p.waitForTimeout(400);
await p.screenshot({path:'/tmp/theme_how.png'});
await p.evaluate(()=>document.querySelector('#garden').scrollIntoView({behavior:'instant'})); await p.waitForTimeout(600);
await p.screenshot({path:'/tmp/theme_garden.png'});
await p.click('.nav__actions button'); await p.waitForTimeout(400);
await p.screenshot({path:'/tmp/theme_login.png'});
console.log('errors', JSON.stringify(errs));
await b.close(); srv.close();
